version: '3'
services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

  log_processor:
    build:
      context: ./log-message-processor  # Path to the subdirectory
      dockerfile: Dockerfile          # (Optional) if your file is named Dockerfile
    container_name: log_processor
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CHANNEL: log_channel

  todos_api:
    build:
      context: ./todos-api
      dockerfile: Dockerfile
    container_name: todos-api
    depends_on:
      - redis
    environment:
      JWT_SECRET: PRFT
      TODOS_API_PORT: 8082
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CHANNEL: todos_api
    ports:
     - "8082:8082"


  auth_api:
   build:
     context: ./auth-api
     dockerfile: Dockerfile
   container_name: auth-api
   environment:
     JWT_SECRET: PRFT
     AUTH_API_PORT: 8000
     USERS_API_ADDRESS: http://user-api:8083
   ports:
     - "8000:8000"

  user_api:
   build:
     context: ./users-api
     dockerfile: Dockerfile
   container_name: user-api
   environment:
     JWT_SECRET: PRFT
     SERVER_PORT: 8083
   ports:
     - "8083:8083"

  frontend:
   build:
     context: ./frontend
     dockerfile: Dockerfile
   container_name: frontend
   depends_on:
     - auth_api
     - todos_api
   environment:
     PORT: 8080
     AUTH_API_ADDRESS: http://auth-api:8000
     TODOS_API_ADDRESS: http://todos-api:8082
     ZIPKIN_URL: http://zipkin:9411/api/v2/spans
   ports:
     - "8080:8080"

  zipkin:
    image: openzipkin/zipkin:2.24
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
