name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build, tag, and push images
      run: |
        # Define a version (e.g., from a GitHub Actions environment variable or hardcoded)
        VERSION=$(date +%Y%m%d%H%M%S)

        # Build and tag images
        docker build -t log-message-processor:latest -t log-message-processor:$VERSION ./log-message-processor
        docker build -t todos-api:latest -t todos-api:$VERSION ./todos-api
        docker build -t auth-api:latest -t auth-api:$VERSION ./auth-api
        docker build -t users-api:latest -t users-api:$VERSION ./users-api
        docker build -t frontend:latest -t frontend:$VERSION ./frontend

        # Push images to Docker Hub
        docker push log-message-processor:latest
        docker push log-message-processor:$VERSION

        docker push todos-api:latest
        docker push todos-api:$VERSION

        docker push auth-api:latest
        docker push auth-api:$VERSION

        docker push users-api:latest
        docker push users-api:$VERSION

        docker push frontend:latest
        docker push frontend:$VERSION